### ISSUE TITLE
Error calling partials

### ISSUE THREAD

**Issue by tknx** [wangchucheng/hugo-eureka#150] opened 2021-12-02 20:05 UTC
**Describe the bug**

On WSL Ubuntu - a cloned repository will not operate effectively

**To Reproduce**

I created a site on github from my mac, when I cloned the repository to my Windows desktop, it fails to execute with errors on calling partials

1. Create site; install eureka using module installation
2. Upload to repository: https://github.com/tknx/thethousandkingdoms
3. Clone on Windows machine
3. Run hugo mod get -u
4. Run hugo server and see error as follows:

```
$ hugo server

Building sites … ERROR 2021/12/02 09:57:43 render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/tarun/thethousandkingdoms/_vendor/wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10": execute of template failed: template: partials/head.html:53:10: executing "partials/head.html" at <partial "get-title" .>: error calling partial: partial "get-title" not found
ERROR 2021/12/02 09:57:43 render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/tarun/thethousandkingdoms/_vendor/wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10": execute of template failed: template: partials/head.html:53:10: executing "partials/head.html" at <partial "get-title" .>: error calling partial: partial "get-title" not found
ERROR 2021/12/02 09:57:43 render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/tarun/thethousandkingdoms/_vendor/wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10": execute of template failed: template: partials/head.html:53:10: executing "partials/head.html" at <partial "get-title" .>: error calling partial: partial "get-title" not found
ERROR 2021/12/02 09:57:43 render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/tarun/thethousandkingdoms/_vendor/wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10": execute of template failed: template: partials/head.html:53:10: executing "partials/head.html" at <partial "get-title" .>: error calling partial: partial "get-title" not found
Built in 29 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/tarun/thethousandkingdoms/_vendor/wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10": execute of template failed: template: partials/head.html:53:10: executing "partials/head.html" at <partial "get-title" .>: error calling partial: partial "get-title" not found
```

**Expected behavior**

Executes cleanly

**Environment**

 -  hugo version: Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z
 - Eureka Version: current

**Additional context**

Thread here on hugo forums for more details: https://discourse.gohugo.io/t/do-i-need-to-re-add-modules-when-using-cloned-repositories/35863

**Comment by wangchucheng** [comment] 2021-12-02 20:08
Do you have go installed on your WSL?

2021年12月2日 15:05，tknx ***@***.******@***.***>> 写道：



Describe the bug

On WSL Ubuntu - a cloned repository will not operate effectively

To Reproduce

I created a site on github from my mac, when I cloned the repository to my Windows desktop, it fails to execute with errors on calling partials

Steps to reproduce the behavior:

  1.  Create site; install eureka using module installation
  2.  Upload to repository: https://github.com/tknx/thethousandkingdoms
  3.  Clone on Windows machine
  4.  Run hugo mod get -u
  5.  Run hugo server and see error as follows:

$ hugo server

Building sites … ERROR 2021/12/02 09:57:43 render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/tarun/thethousandkingdoms/_vendor/wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10<http://wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10>": execute of template failed: template: partials/head.html:53:10: executing "partials/head.html" at <partial "get-title" .>: error calling partial: partial "get-title" not found
ERROR 2021/12/02 09:57:43 render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/tarun/thethousandkingdoms/_vendor/wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10<http://wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10>": execute of template failed: template: partials/head.html:53:10: executing "partials/head.html" at <partial "get-title" .>: error calling partial: partial "get-title" not found
ERROR 2021/12/02 09:57:43 render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/tarun/thethousandkingdoms/_vendor/wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10<http://wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10>": execute of template failed: template: partials/head.html:53:10: executing "partials/head.html" at <partial "get-title" .>: error calling partial: partial "get-title" not found
ERROR 2021/12/02 09:57:43 render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/tarun/thethousandkingdoms/_vendor/wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10<http://wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10>": execute of template failed: template: partials/head.html:53:10: executing "partials/head.html" at <partial "get-title" .>: error calling partial: partial "get-title" not found
Built in 29 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/tarun/thethousandkingdoms/_vendor/wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10<http://wangchucheng.com/hugo-eureka/layouts/partials/head.html:53:10>": execute of template failed: template: partials/head.html:53:10: executing "partials/head.html" at <partial "get-title" .>: error calling partial: partial "get-title" not found


Expected behavior

Executes cleanly

Environment

  *   hugo version: Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z
  *   Eureka Version: current

Additional context

Thread here on hugo forums for more details: https://discourse.gohugo.io/t/do-i-need-to-re-add-modules-when-using-cloned-repositories/35863

**Comment by tknx** [comment] 2021-12-02 20:37
$ go version
go version go1.13.8 linux/amd64

Looks good?

**Comment by wangchucheng** [comment] 2021-12-02 20:42
Yeah, I think this should work. If this is a reproducible issue, it may be a platform-related issue with Hugo. But I do not have a windows machine right now, so I’m afraid that I may not be able to test this for you.

2021年12月2日 15:38，tknx ***@***.******@***.***>> 写道：



$ go version
go version go1.13.8 linux/amd64

Looks good?

**Comment by tknx** [comment] 2021-12-02 20:53
I think it must be since the other person I was testing with had no problems when they cloned it to their mac.

**Comment by tknx** [comment] 2021-12-03 22:09
Ok this is related to something with the WSL. When I installed Hugo through windows and scoop it works fine.

**Comment by wangchucheng** [comment] 2021-12-11 02:48
Since this is an issue with Hugo instead of Eureka, I will close this issue for now. ;-)

**Closed by wangchucheng** 2021-12-11 02:48 UTC
Labels: bug
